.

diff --git a/.github/workflows/run_e2e_on_ref_local.yml b/.github/workflows/run_e2e_on_ref_local.yml
--- a/.github/workflows/run_e2e_on_ref_local.yml
+++ b/.github/workflows/run_e2e_on_ref_local.yml
@@ -28,10 +28,10 @@ jobs:
 #        username: ${{ github.actor }}
 #        password: ${{ secrets.GITHUB_TOKEN }}
     steps:
-    - name: 'Cleanup build folder'
-      run: |
-        rm -rf ./* || true
-        rm -rf ./.??* || true
+#    - name: 'Cleanup build folder'
+#      run: |
+#        rm -rf ./* || true
+#        rm -rf ./.??* || true
 
     - name: dircheck_initial
       run: |
@@ -44,7 +44,9 @@ jobs:
         ls -la /__w/datalens-backend/datalens-backend/datalens-backend || true
 
     - name: Checkout datalens-ui repo
-      run: git clone https://github.com/datalens-tech/datalens-ui.git /__w/datalens-backend/datalens-backend/datalens-ui
+      run: git clone https://github.com/datalens-tech/datalens-ui.git datalens-ui
+#      run: git clone https://github.com/datalens-tech/datalens-ui.git /__w/datalens-backend/datalens-backend/datalens-ui
+
 #      uses: actions/checkout@v4
 #      with:
 #        repository: datalens-tech/datalens-ui
@@ -65,13 +67,16 @@ jobs:
         ls -la /__w/datalens-backend/datalens-backend || true
 
     - name: Checkout code
-      run: git clone https://github.com/datalens-tech/datalens-backend.git /__w/datalens-backend/datalens-backend/datalens-backend
+      run: git clone https://github.com/datalens-tech/datalens-backend.git /datalens-backend
+#      run: git clone https://github.com/datalens-tech/datalens-backend.git /__w/datalens-backend/datalens-backend/datalens-backend
+
 #      uses: actions/checkout@v2
 #      with:
 #        path: /__w/datalens-backend/datalens-backend/datalens-backend
 
     - name: dircheck
       run: |
+        pwd
         ls -la
         ls -la ../
         ls -la /__w || true
@@ -85,12 +90,14 @@ jobs:
 #        REPOSITORY_NAME: ${{ github.event.repository.name }}
 
     - name: Switch to PR head
-      working-directory: /__w/datalens-backend/datalens-backend/datalens-backend
+#      working-directory: /__w/datalens-backend/datalens-backend/datalens-backend
+      working-directory: ./datalens-backend
       run: gh pr checkout ${{ github.event.inputs.pr }}
       env:
         GH_TOKEN: ${{ github.token }}
     - name: Validate SHA
-      working-directory: /__w/datalens-backend/datalens-backend/datalens-backend
+#      working-directory: /__w/datalens-backend/datalens-backend/datalens-backend
+      working-directory: ./datalens-backend
       run: |
         export HEAD_SHA=$(git rev-parse HEAD)
         export INPUT_SHA="${{ github.event.inputs.sha }}"
@@ -112,6 +119,7 @@ jobs:
 #        path: tools/e2e/datalens-ui
     - name: dircheck
       run: |
+        pwd
         ls -la
         ls -la ../
         ls -la /__w || true
@@ -122,11 +130,12 @@ jobs:
         node-version: 18
         cache: 'npm'
 #        cache-dependency-path: ../datalens-ui/package-lock.json
-        cache-dependency-path: /__w/datalens-backend/datalens-backend/datalens-ui/package-lock.json
+        cache-dependency-path: ./datalens-ui/package-lock.json
 
     - name: dircheck
-      working-directory: datalens-backend
+      working-directory: ./datalens-backend
       run: |
+        pwd
         ls -la
         ls -la ../
         ls -la /__w || true
@@ -135,5 +144,5 @@ jobs:
         ls -la /__w/datalens-backend/datalens-backend/datalens-ui || true
 
     - name: Build and run E2E
-      working-directory: /__w/datalens-backend/datalens-backend/datalens-backend
+      working-directory: ./datalens-backend
       run: task e2e:init-and-run DATALENS_UI_FOLDER="../../../datalens-ui"
